Support default setting overrides on different languages
yomidevs/yomitan pull request #1368
Opened 2024-08-28 18:31 UTC by jamesmaa

Fixes #1328

2024-08-29 06:30 UTC, jamesmaa commented on ext/js/pages/settings/languages-controller.js
> +        languageSelect.addEventListener(
This is actually kind of brittle. To prompt users whether they'd like to update the current profile settings upon changing the language selection dropdown is falsely triggered by the following scenarios:

- When I change profiles which update the language selected
- When I load the page and the `prepare()` statement runs, changing the value (this is guarded via a clause)

If someone knows how to guard against the first condition OR know a better place to hook this logic, that would be great

2024-10-17 18:12 UTC, Kuuuube requested changes

2024-10-18 14:27 UTC, jamesmaa commented
comments addressed. current look 
<img width="682" alt="image" src="https://github.com/user-attachments/assets/06b35a56-f749-44e5-8a05-9e87d13dbe80">

<img width="654" alt="image" src="https://github.com/user-attachments/assets/1121a209-1a03-4b63-9daf-0a5dd808acdd">

2024-10-23 04:04 UTC, Kuuuube approved these changes
I think this is fine to merge but I feel like we should probably add overrides to turn off the scan whole word stuff when selecting japanese, chinese, cantonese, and korean.

2024-10-25 18:08 UTC, merged

2024-10-26 10:29 UTC, MarvNC commented
![msedge_Support_default_setting_overrides_on_different_lan_2024-10-26_03-27-42](https://github.com/user-attachments/assets/0f21130c-e900-4c6d-8df1-2fdd48b17873)

Playwright breakage seems to have been caused by this PR