Add turning-off of parser for languages with spaces in recommended settings
yomidevs/yomitan pull request #1592
Opened 2024-11-19 15:46 UTC by liuwllm

Closes #1573 

Adds two settings to languages with spaces:
- Set parsing.enableScanningParser to false to turn off internal parser
- Set parsing.termSpacing to false to remove added spaces between parsed words

2024-11-19 15:57 UTC, Kuuuube commented
What does termspacing do when the parser is turned off?

2024-11-19 16:19 UTC, liuwllm commented
Realizing this is a bit redundant if the space is only added to parsed words anyway; will add another commit to remove this from recommended settings

2024-11-21 03:47 UTC, Kuuuube approved these changes

2024-11-21 03:54 UTC, Kuuuube requested changes

2024-11-21 03:54 UTC, Kuuuube commented on ext/data/recommended-settings.json
> +    ],
Is this a mistake?

2024-11-21 04:01 UTC, Kuuuube commented on ext/data/recommended-settings.json
> +    ],
Nvm korean characters look kindof like the space is part of the character or font and tricked me.

2024-11-23 17:50 UTC, Kuuuube approved these changes

2024-11-23 17:53 UTC, merged